sudo: false
dist: trusty
language: python
python:
  - "3.4"

cache:
  pip: true
  directories:
  - $PWD/tmp

addons:
  apt:
    packages:
    - libsaxonb-java
    - default-jre
    - inkscape

install:
 - "pip install -r requirements.txt"
 - "mkdir -p ~/.fonts"
 - "cp fonts/*.otf ~/.fonts/"

script: ./build.sh

after_success:
    - ./deploy.sh
